SELECT DISTINCT [UserAccount].[UserAccount_id]
        ,[Manager].[manager_id]
        ,[UserAccount].[email]
        ,[UserAccount].[AccountName]
        ,[UserAccount].[Pass]
        ,[Manager].[MgAccountName]
        ,[Manager].[MgPass]
        ,[Manager].[MgEmail]
FROM [dbo].[UserAccount], [dbo].[Manager] 
WHERE [UserAccount].[UserAccount_id] != [Manager].[manager_id]