SELECT DISTINCT [UserAccount].[UserAccount_id]
        ,[UserAccount].[email]
        ,[UserAccount].[AccountName]
        ,[UserAccount].[Pass]
        ,[UserAccount].[Full_Name]
        ,[UserAccount].[phone_number]
        ,[UserAccount].[DiaDiem]
        ,[UserAccount].[Gender]
        ,[UserAccount].[ImgUser]
        ,[UserAccount].[Age]
FROM [dbo].[UserAccount]