CREATE TABLE KHACH (
    MAKH INT PRIMARY KEY,
    TENCTY NVARCHAR(100),
    DCHICTY NVARCHAR(100),
    NGUOIDAIDIEN NVARCHAR(100),
    SDT NVARCHAR(20)
);

CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY,
    HO NVARCHAR(50),
    TEN NVARCHAR(50),
    NGAYSINH DATE,
    NGAYVAOLAM DATE,
    DCHI NVARCHAR(100)
);

CREATE TABLE HANGHOA (
    MAHG INT PRIMARY KEY,
    TENHG NVARCHAR(100),
    DGIA DECIMAL(10, 2)
);

CREATE TABLE DONHANG (
    MADDH INT PRIMARY KEY,
    MAKH INT,
    MANV INT,
    NGAYDAT DATE,
    NGAYPHAIGIAO DATE,
    DCHIGIAO NVARCHAR(100),
    TPHOGIAO NVARCHAR(50),
    TRIGIA DECIMAL(10, 2),
    FOREIGN KEY (MAKH) REFERENCES KHACH(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE CT_DDH (
    MADDH INT,
    MAHG INT,
    SL INT,
    DONGIA DECIMAL(10, 2),
    TiLeCK NUMERIC(3, 2) DEFAULT 0,
    FOREIGN KEY (MADDH) REFERENCES DONHANG(MADDH),
    FOREIGN KEY (MAHG) REFERENCES HANGHOA(MAHG)
);