USE QLNhanSuDb;

CREATE TABLE PHONGBAN
(
	MAPHG INT PRIMARY KEY,
	TENPHG NCHAR(20),
	TRPHG NCHAR(9),
	NG_NHANCHUC DATE
);

ALTER TABLE dbo.PHONGBAN
	DROP COLUMN TENPHG
GO

ALTER TABLE dbo.PHONGBAN
	ADD TENPHG NVARCHAR(20)
GO

CREATE TABLE DEAN
(
	MADA INT PRIMARY KEY,
	TENDA NCHAR(15),
	DDIEM_DA NCHAR(15),
	PHONG INT,
	FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)
);

CREATE TABLE DIADIEM_PHG
(
	MAPHG INT,
	DIADIEM NCHAR(15),
	PRIMARY KEY (MAPHG, DIADIEM),
	FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

CREATE TABLE NHANVIEN
(
	MANV NCHAR(9) PRIMARY KEY,
	HONV NCHAR(15),
	TENLOT NCHAR(15),
	TENNV NCHAR(15),
	NGSINH DATE,
	DCHI NCHAR(30),
	PHAI NCHAR(3),
	LUONG INT,
	MA_NQL NCHAR(9),
	PHG INT,

	FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)
);

ALTER TABLE PHONGBAN
ADD FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV);


CREATE TABLE THANHNHAN
(
	MA_NVIEN NCHAR(9),
	TENTN NCHAR(15),
	PHAI NCHAR(3),
	NGSINH DATE,
	QUANHE NCHAR(15),
	PRIMARY KEY (MA_NVIEN, TENTN),
	FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE PHANCONG
(
	MA_NVIEN NCHAR(9),
	MADA INT,
	THOIGIAN INT,
	PRIMARY KEY (MA_NVIEN, MADA),
	FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
);

