-- Drop the table 'TableName' in schema 'SchemaName'

    DROP TABLE dbo.PHANCONG
    
    DROP TABLE dbo.CONGVIEC

-- CÂU 1
DELETE FROM [NHANVIEN]
WHERE [MANV] NOT IN (
    SELECT [MA_NVIEN] FROM [PHANCONG]
    INNER JOIN [DUAN] ON [DUAN].[MADA] = [PHANCONG].[SODA]
    )

-- CÂU 2
DELETE FROM [NHANVIEN]
WHERE NOT EXISTS (
    SELECT 1
    FROM THANNHAN
    WHERE THANNHAN.MA_NVIEN = [NHANVIEN].MANV
);