-- Cau 1
UPDATE NHANVIEN
SET
    [DCHI] = N'TP Hồ Chí Minh'
WHERE [DCHI] IS NULL
GO

-- Cau 2
UPDATE NHANVIEN
SET [PHG] = 
    CASE 
        WHEN CAST([MANV] AS INT) BETWEEN 1 AND 10 THEN 2
        WHEN CAST([MANV] AS INT) BETWEEN 11 AND 40 THEN 6
        WHEN CAST([MANV] AS INT) BETWEEN 41 AND 80 THEN 7
        WHEN CAST([MANV] AS INT) BETWEEN 102 AND 200 THEN 5
    END

-- Cau 3
UPDATE NHANVIEN
SET [NGSINH] = '1985-01-01'
WHERE [NGSINH] IS NULL

-- Cau 4
UPDATE NHANVIEN
SET LUONG = 
   CASE 
       WHEN PHG IN (SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Nghiên cứu') THEN 100000
       WHEN PHG IN (SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Kế Toán') THEN 65000
       WHEN PHG IN (SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Kỹ Thuật') THEN 85000
       WHEN PHG IN (SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Nhân Sự') THEN 70000
   END
FROM NHANVIEN
WHERE PHG IN (SELECT MAPHG FROM PHONGBAN WHERE TENPHG IN (N'Nghiên cứu', N'Kế Toán', N'Kỹ Thuật', N'Nhân sự'))


-- Cau 5
UPDATE NHANVIEN
SET MA_NQL = (
    SELECT NV.MANV
    FROM NHANVIEN NV
    INNER JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
    WHERE NV.MANV = NHANVIEN.MANV
)

-- Module 4
-- 3.
   DECLARE @manv CHAR(9)  
   DECLARE email_cursor CURSOR  
   FOR SELECT MANV FROM NHANVIEN  
   OPEN email_cursor  
   FETCH NEXT FROM email_cursor INTO @manv 
   WHILE @@FETCH_STATUS = 0  
   BEGIN  
   UPDATE NHANVIEN  
   SET Email = 'User_' + @manv + '@mail.com'  
   WHERE MANV = @manv 
   FETCH NEXT FROM email_cursor INTO @manv 
   END  
   CLOSE email_cursor  
   DEALLOCATE email_cursor

